apiVersion: v1
kind: Namespace
metadata:
    name: $org

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: $pvName
#spec:
#  capacity:
#    storage: 500Mi
#  accessModes:
#    - ReadWriteMany
#  nfs:
#    path: $path
#    server: 10.112.122.9  #change to your nfs server ip here
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
# namespace: $org
# name: $pvName
#spec:
# accessModes:
#   - ReadWriteMany
# resources:
#   requests:
#     storage: 10Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
  labels:
    pv-name: $pvName
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: fs-bb629dc2.efs.us-east-2.amazonaws.com
    path: $path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $org
  name: $pvName
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv-name: $pvName
  resources:
    requests:
      storage: 10Mi

