apiVersion: v1
kind: Namespace
metadata:
    name: $org

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: $pvName
#spec:
#  capacity:
#    storage: 500Mi
#  accessModes:
#    - ReadWriteMany
#  nfs:
#    path: $path
#    server: 10.112.122.9  #change to your nfs server ip here
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
# namespace: $org
# name: $pvName
#spec:
# accessModes:
#   - ReadWriteMany
# resources:
#   requests:
#     storage: 10Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $org
  name: $pvName
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
